#!/usr/bin/env bash
# shellcheck disable=SC2199
# shellcheck source=/dev/null
#
# Copyright (C) 2020-22 UtsavBalar1231 <utsavbalar1231@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Enviromental Variables
DATE=$(date +"%d.%m.%y")
OUT_DIR=$(pwd)/out/
FILENAME=${OUT_DIR}/boot.img
KERNEL_IMAGE="${OUT_DIR}/arch/arm64/boot/Image"
DTB_FILE="${OUT_DIR}/arch/arm64/boot/dts/rockchip/rk3399-rock-pi-4b.dtb"

if [[ -z "${KEBABS}" ]]; then
    COUNT="$(grep -c '^processor' /proc/cpuinfo)"
    export KEBABS="$((COUNT * 2))"
fi

ARGS="ARCH=arm64 \
O=${OUT_DIR} \
CROSS_COMPILE=aarch64-linux-gnu-
CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
-j${KEBABS}"

export CROSS_COMPILE=aarch64-linux-gnu-

if [[ "$@" =~ "debian"* ]]; then
	echo -e "###### USING DEBIAN EXTLINUX CONFIG #####"
	EXTLINUX_CONF=extlinux/rk3399-debian.conf
else
	echo -e "###### USING MANAJRO EXTLINUX CONFIG #####"
	EXTLINUX_CONF=extlinux/rk3399-manjaro.conf
fi

rm ${KERNEL_IMAGE} ${DTB_FILE} ${FILENAME}
rm -r ${OUT_DIR}/extlinux/

# Make defconfig
make -j${KEBABS} ${ARGS} nanopi4_linux_defconfig

# Make kernel Image
make -j${KEBABS} ${ARGS} CC="ccache ${CROSS_COMPILE}gcc" 2>&1 | tee build.log

# Pack Image into boot image
mkfs.vfat -n "boot" -S 512 -C $FILENAME $((100 * 1024))

cp -vr extlinux $OUT_DIR

cd $OUT_DIR

mmd -i $FILENAME ::/extlinux
mcopy -i $FILENAME -s $EXTLINUX_CONF ::/extlinux/extlinux.conf
mcopy -i $FILENAME -s $KERNEL_IMAGE ::
mcopy -i $FILENAME -s $DTB_FILE ::/rk3399-rockpi4b-linux.dtb

cd $(pwd) || exit
